### ISSUE TITLE
Maintainer Audit!

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/montpelier-trails#1]
:wave: Hey there! This is the developer experience audit from @mntnr for this repository. I've added in my thoughts below, in the form of a checklist. Looking forward to seeing what you think; let's see if we can resolve all of the open issues and make this repository shine ✨ 💖 ✨

# Repository Review: [RichardLitt/montpelier-trails](https://github.com/RichardLitt/montpelier-trails)

> Interactive map of trails in Montpelier, VT

_For notes on anything crossed out, look below. Note: I use `[~]` to mean that I have proposed a fix in a PR. I know it doesn't render properly in Markdown, but it works pretty well otherwise for that purpose. If I think that something is fine, even if it isn't valid according to this checklist, I've checked it off and included a note._

### Reviewing the Repository Docs

- [x] Is there a README?
  - [x] Does it follow [standard-readme](https://github.com/RichardLitt/standard-readme)?
  - [x] Is it spellchecked?
- [x] Is there a Code of Conduct, such as the [Contributor Covenant](https://github.com/simonv3/covenant-generator)?
  - [x] Is it mentioned in the Contribute section of the README? (Note: this isn't needed if you mention it in your CONTRIBUTE.md and it is in this repository.)
  - [x] Does it reference an email address for violations?
- [x] Is there a `LICENSE` file?
  - [x] Is this matched in the `package.json`?
  - [x] Is the year correct?
- [x] Does this pass [`alex`](https://github.com/wooorm/alex) adequately? Run `alex *.md`.
- [x] Does the repository name itself pass on http://wordsafety.com?

### Process
- [x] Can I install easily?
- [x] Can I use this easily?

### Issues and Pull Requests
- [x] Are there an acceptable amount of pull requests?
- [x] Are there an acceptable amount of issues?
- [x] Are an acceptable amount of issues less than six months old?
- [x] Are there useful issue labels?
- [x] Are the labels being used?

### Metadata
- [x] Is there a description on GitHub?
  - [x] Does the description match the README?
- [x] Are the topics useful?

### Package Metadata

Note: These should apply to `package.json` (JavaScript), `*.cabal` (Haskell), and `metadata.yml` (Perl), among others.

- [x] Does the description match the GitHub description?
- [x] Is there a `bugs` field?
- [x] Is there a `homepage` field?
- [x] Are there appropriate `keywords`?
  - [x] Do these match the topics on GitHub?

### TODO

Nothing! \o/

## Contribute back?

This checklist is open source! If you have suggestions or think it could be better, contribute back on [mntnr/audit-templates](https://github.com/mntnr/audit-templates).

Thank you!
